In [22]:
from vnstock import Listing
listing = Listing(source="MSN")
listing.symbols_by_exchange('HSX')

RetryError: RetryError[<Future at 0x1fd85dd97d0 state=finished raised NotImplementedError>]

In [9]:
listing.all_symbols()['symbol']

NameError: name 'listing' is not defined

In [1]:
from vnstock import Trading
trading = Trading(source='vci',symbol='VCB').price_board(['VCB','ACB','TCB','BID','AAA'])

AttributeError: partially initialized module 'vnai' has no attribute 'setup' (most likely due to a circular import)

In [27]:
trading.columns

MultiIndex([('listing',                 'symbol'),
            ('listing',                'ceiling'),
            ('listing',                  'floor'),
            ('listing',              'ref_price'),
            ('listing',             'stock_type'),
            ('listing',               'exchange'),
            ('listing',         'trading_status'),
            ('listing',        'security_status'),
            ('listing',      'last_trading_date'),
            ('listing',             'issue_date'),
            ('listing',           'listed_share'),
            ('listing',            'coupon_rate'),
            ('listing',                  'yield'),
            ('listing',           'sending_time'),
            ('listing',                   'type'),
            ('listing',             'organ_name'),
            ('listing',         'mapping_symbol'),
            ('listing',         'product_grp_id'),
            ('listing',              'partition'),
            ('listing',             'index_type'),
            ('listing',           'trading_date'),
            ('listing',     'lst_trading_status'),
            ('bid_ask',       'transaction_time'),
            ('bid_ask',              'bid_count'),
            ('bid_ask',              'ask_count'),
            (  'match',      'accumulated_value'),
            (  'match',     'accumulated_volume'),
            (  'match',   'accumulated_value_g1'),
            (  'match',  'accumulated_volume_g1'),
            (  'match',        'avg_match_price'),
            (  'match',           'current_room'),
            (  'match',     'foreign_buy_volume'),
            (  'match',    'foreign_sell_volume'),
            (  'match',      'foreign_buy_value'),
            (  'match',     'foreign_sell_value'),
            (  'match',                'highest'),
            (  'match',                 'lowest'),
            (  'match',            'match_price'),
            (  'match',             'open_price'),
            (  'match', 'first_time_match_price'),
            (  'match',             'match_type'),
            (  'match',              'match_vol'),
            (  'match',           'sending_time'),
            (  'match',             'total_room'),
            (  'match',       'total_buy_orders'),
            (  'match',      'total_sell_orders'),
            (  'match',              'bid_count'),
            (  'match',              'ask_count'),
            (  'match',             'underlying'),
            (  'match',          'open_interest'),
            (  'match',             'stock_type'),
            (  'match',              'partition'),
            (  'match',         'is_match_price'),
            (  'match',          'ceiling_price'),
            (  'match',            'floor_price'),
            (  'match',        'reference_price'),
            ('bid_ask',            'bid_1_price'),
            ('bid_ask',           'bid_1_volume'),
            ('bid_ask',            'bid_2_price'),
            ('bid_ask',           'bid_2_volume'),
            ('bid_ask',            'bid_3_price'),
            ('bid_ask',           'bid_3_volume'),
            ('bid_ask',            'ask_1_price'),
            ('bid_ask',           'ask_1_volume'),
            ('bid_ask',            'ask_2_price'),
            ('bid_ask',           'ask_2_volume'),
            ('bid_ask',            'ask_3_price'),
            ('bid_ask',           'ask_3_volume')],
           )

In [7]:
from datetime import datetime , timedelta
start = datetime.now() - timedelta(minutes=5)
start = start.strftime("%Y-%m-%d %H:%M:%S")
end = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(start)

2025-09-17 08:14:05

In [2]:
from vnstock import Quote
from datetime import datetime , timedelta   
start_date = '2024-06-20'
end_date = '2024-06-20'
print(start_date)
quote = Quote(symbol='vci', source='vci')
            # symbol (str, optional): Stock symbol. Mã chứng khoán.
            # start (str): Start time in format YYYY-MM-DD or YYYY-MM-DD HH:MM:SS.
            #             Thời gian bắt đầu định dạng YYYY-MM-DD hoặc YYYY-MM-DD HH:MM:SS.
            # end (str): End time in format YYYY-MM-DD or YYYY-MM-DD HH:MM:SS.
            #           Thời gian kết thúc định dạng YYYY-MM-DD hoặc YYYY-MM-DD HH:MM:SS.
            # interval (str, optional): Data interval (1m, 5m, 15m, 30m, 1H, D, 1W, 1M).
            #                          Khoảng thời gian dữ liệu (1m, 5m, 15m, 30m, 1H, 
data =quote.history(start=start_date, end=end_date,interval ='1m')
data

2024-06-20

                   time   open   high    low  close  volume
0   2024-06-20 09:15:00  37.13  37.13  37.13  37.13    1600
1   2024-06-20 09:16:00  37.13  37.24  37.13  37.24    2200
2   2024-06-20 09:17:00  37.24  37.28  37.24  37.28    1000
3   2024-06-20 09:18:00  37.28  37.39  37.28  37.39     500
4   2024-06-20 09:19:00  37.39  37.39  37.32  37.32    2900
..                  ...    ...    ...    ...    ...     ...
212 2024-06-20 14:26:00  36.98  37.01  36.98  36.98   22100
213 2024-06-20 14:27:00  36.98  36.98  36.98  36.98   14100
214 2024-06-20 14:28:00  36.98  36.98  36.94  36.98   11700
215 2024-06-20 14:29:00  36.98  36.98  36.90  36.94   22700
216 2024-06-20 14:45:00  36.86  36.86  36.86  36.86  221900

[217 rows x 6 columns]

In [1]:
quote = Quote(symbol='tcb', source='vci')
data = quote.history(start='2025-09-17', end='2025-09-17',interval = '1m')
record = {
    "time": data["date"].iloc[-1].strftime("%Y-%m-%d %H:%M:%S"),
    "open": data["open"].iloc[-1],
    "high": data["high"].iloc[-1],
    "low": data["low"].iloc[-1],
    "close": data["close"].iloc[-1],
}

NameError: name 'Quote' is not defined

In [7]:
from vnstock import Vnstock
stock = Vnstock().stock(symbol='TCB', source='VCI')
inday = stock.quote.intraday(page_size=1, show_log=False)
inday

ConnectionError: Failed to fetch data: 502 - Bad Gateway

In [29]:
?stock.quote.intraday

Signature: stock.quote.intraday(symbol: Optional[str] = None, **kwargs)
Docstring: <no docstring>
File:      e:\data_eng\seminar\env\lib\site-packages\vnstock\common\data\data_explorer.py
Type:      method

In [81]:
from vnstock import Vnstock
company = Vnstock().stock(symbol='AAA', source='tcbs').company
company.overview()

2025-09-11 23:10:29 - vnstock.common.data.data_explorer - INFO - TCBS không cung cấp thông tin danh sách. Dữ liệu tự động trả về từ VCI.

,symbol,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2
0,AAA,HOSE,Chemicals,CT,27697,0.019,393.7,382.3,2007,4723,2.5,-0.016,-0.119,-0.466,An Phat Bioplastics,https://anphatbioplastics.com,150,1353

In [70]:
from vnstock import Vnstock
?Vnstock.stock.company

Object `Vnstock.stock.company` not found.

In [83]:
from vnstock import Company
company = Company(symbol='VIB', source='tcbs')
company.overview()

,symbol,exchange,industry,company_type,no_shareholders,foreign_percent,outstanding_share,issue_share,established_year,no_employees,stock_rating,delta_in_week,delta_in_month,delta_in_year,short_name,website,industry_id,industry_id_v2
0,VIB,HOSE,Banks,NH,29187,0.05,3404.0,3404.0,1996,11736,2.6,-0.062,-0.009,0.07,VIBBank,https://www.vib.com.vn,289,8355

In [2]:
from vnstock import Company
company = Company(symbol='VIB', source='VCI')
company.news()['

,id,news_title,news_sub_title,friendly_sub_title,news_image_url,news_source_link,created_at,public_date,updated_at,lang_code,news_id,news_short_content,news_full_content,close_price,ref_price,floor,ceiling,price_change_pct
0,8323567,VIB: Thông báo về việc thay đổi ngày giao dịch...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-thong-bao-ve...,None,1756138620000,None,vi,11684364,,<p>Sở Giao dịch Chứng khoán Thành phố Hồ Chí M...,21950,23600,21950,25250,-0.069915
1,8323566,VIB: Thông báo về việc giao dịch chứng khoán t...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-thong-bao-ve...,None,1756117800000,None,vi,11684363,,<p>Sở Giao dịch Chứng khoán Thành phố Hồ Chí M...,21950,23600,21950,25250,-0.069915
2,8294653,VIB: Quyết định về việc thay đổi đăng ký niêm yết,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-quyet-dinh-v...,None,1755876360000,None,vi,11682552,,<p>Sở Giao dịch Chứng khoán Thành phố Hồ Chí M...,23600,23400,21800,25000,0.008547
3,8285638,VIB: Nghị quyết HĐQT về việc phê duyệt kế hoạc...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-nghi-quyet-h...,None,1755792390000,None,vi,11680973,,<p>Ngân hàng Thương mại Cổ phần Quốc tế Việt N...,23400,21900,20400,23400,0.068493
4,8238449,VIB: Thông báo quyết định của NHNN về việc sửa...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-thong-bao-qu...,None,1755253806000,None,vi,11674405,,<p>Ngân hàng Thương mại Cổ phần Quốc tế Việt N...,20350,20450,19050,21850,-0.004890
5,8164195,VIB: Báo cáo kết quả giao dịch cổ phiếu của ng...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-bao-cao-ket-...,None,1754579690000,None,vi,11666029,,<p> Vũ Thị Thu Hiền báo cáo kết quả giao dịch ...,19550,19500,18150,20850,0.002564
6,8092944,VIB: Thông báo công văn của UBCKNN về việc nhậ...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-thong-bao-co...,None,1753985861000,None,vi,11658388,,<p>Ngân hàng Thương mại Cổ phần Quốc tế Việt N...,19400,19350,18000,20700,0.002584
7,8067354,VIB: Báo cáo tình hình quản trị công ty 06 thá...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-bao-cao-tinh...,None,1753887871000,None,vi,11655511,,<p>Ngân hàng Thương mại Cổ phần Quốc tế Việt N...,19350,18550,17300,19800,0.043127
8,8056124,VIB: Giải trình biến động LNST quý 2/2025 so v...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-giai-trinh-b...,None,1753723320000,None,vi,11651701,,<p>Ngân hàng Thương mại Cổ phần Quốc tế Việt N...,18850,18400,17150,19650,0.024457
9,8047276,VIB: Báo cáo kết quả giao dịch cổ phiếu của ng...,,,https://cdn.fiingroup.vn/medialib/127889/I/202...,https://www.hsx.vn/vi/tin-tuc/vib-bao-cao-ket-...,None,1753715065000,None,vi,11651398,,<p>Nguyễn Xuân Dũng báo cáo kết quả giao dịch ...,18850,18400,17150,19650,0.024457

In [14]:
from vnstock import Vnstock
stock = Vnstock().stock(symbol='TCB', source='vci')
in_day = stock.quote.intraday(page_size=5, show_log=False)
print(in_day)
records = []
for _, row in in_day.iterrows():
    record = {
        "id": row["id"],
        "symbol": 'TCB',
        "price": row["price"],    # giá khớp lệnh
        "volume": row["volume"],    # khối lượng khớp lệnh
        "type": row["match_type"],            # buy / sell
        "time": row["time"].strftime("%Y-%m-%d %H:%M:%S"),    
    }
    records.append(record)

                       time  price  volume match_type         id
0 2025-09-18 14:45:00+07:00   38.8    1000        Buy  367305164
1 2025-09-18 14:45:00+07:00   38.8     100        Buy  367305163
2 2025-09-18 14:45:00+07:00   38.8     100        Buy  367305162
3 2025-09-18 14:45:00+07:00   38.8     100        Buy  367305161
4 2025-09-18 14:45:00+07:00   38.8     300        Buy  367305160

In [13]:
print(records)

[{'id': '367305164', 'symbol': 'TCB', 'price': 38.8, 'volume': 1000, 'type': 'Buy', 'time': '2025-09-18 14:45:00'}]

In [12]:
from vnstock import Company
company = Company(symbol='ACB', source='vci')
company

In [15]:
company.overview()['company_profile'].iloc[0]

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

'Ngân hàng Thương mại Cổ phần Á Châu (ACB) được thành lập năm 1993. Ngân hàng hoạt động trong lĩnh vực huy động, kinh doanh vốn và cung cấp các dịch vụ tài chính liên quan. Năm 2024, so với cùng kỳ, Biên lãi thuần (NIM) ở mức 3.6%, giảm 0.27%. Tỷ lệ nợ xấu ở mức 1.49%, tăng 0.28%. Tỷ lệ bao phủ nợ xấu ở mức 77.92%, giảm 13.25%. Lợi nhuận sau thuế công ty mẹ có giá trị bằng 16,8 nghìn tỷ đồng, tăng 4.64%. Tỷ suất lợi nhuận trên vốn chủ sở hữu (ROE) ở mức 21.75%, giảm 3.05%. Ngày 09/12/2020, ACB chính thức giao dịch trên Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh (HOSE).'

In [46]:
reports['name'].iloc[2]

'TCB [KHẢ QUAN +10,7%] - Chiến lược hệ sinh thái thúc đẩy tăng trưởng bền vững - Cập nhật'

In [10]:
company.events()

,id,event_title,en__event_title,public_date,issue_date,source_url,event_list_code,ratio,value,record_date,exright_date,event_list_name,en__event_list_name
0,18131,Trả cổ tức bằng tiền mặt,,2011-04-14,2011-05-12,,DIV,NaN,NaN,2011-04-25,2011-04-21,Trả cổ tức bằng tiền mặt,Cash Dividend
1,18152,ACB - Niêm yết bổ sung 440.690 cổ phiếu,"ACB - Lists additional 440,690 shares",2021-07-16,2022-04-19,http://fiinpro.com/News/Detail/8195547?lang=vi-VN,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
2,18135,Trả cổ tức bằng tiền mặt,,2013-05-10,2013-06-04,,DIV,NaN,NaN,2013-05-21,2013-05-17,Trả cổ tức bằng tiền mặt,Cash Dividend
3,18128,Trả cổ tức bằng tiền mặt,,2010-10-29,2010-11-30,,DIV,NaN,NaN,2010-11-10,2010-11-08,Trả cổ tức bằng tiền mặt,Cash Dividend
4,18137,Trả cổ tức bằng tiền mặt,,2014-04-29,2014-05-30,,DIV,NaN,NaN,2014-05-15,2014-05-13,Trả cổ tức bằng tiền mặt,Cash Dividend
5,18129,Phát hành cổ phiếu,,2010-11-18,2010-11-30,,ISS,NaN,NaN,2010-11-30,2010-11-26,Phát hành cổ phiếu,Share Issue
6,18140,ACB-Phát hành cổ phiếu trả cổ tức cho CĐHH tỷ ...,ACB-Issues dividend shares for existing shareh...,2016-11-21,2016-12-01,http://fiinpro.com/News/Detail/313345?lang=vi-VN,ISS,NaN,NaN,2016-12-02,2016-12-01,Phát hành cổ phiếu,Share Issue
7,18142,ACB-Trả cổ tức bằng cổ phiếu cho cổ đông hiện ...,ACB-Issues dividend shares for existing shareh...,2018-03-14,2018-03-20,http://fiinpro.com/News/Detail/1564876?lang=vi-VN,ISS,0.10,0.0,2018-03-21,2018-03-20,Phát hành cổ phiếu,Share Issue
8,18144,ACB-Phát hành cổ phiếu trả cổ tức tỷ lệ 15%,ACB-Issues dividend shares at 15%,2018-08-29,2018-09-06,http://fiinpro.com/News/Detail/2278207?lang=vi-VN,ISS,0.15,0.0,2018-09-07,2018-09-06,Phát hành cổ phiếu,Share Issue
9,18148,ACB- Phát hành cổ phiếu trả cổ tức tỷ lệ 30%,ACB- Issues dividend shares at 30%,2020-08-14,2020-08-20,http://fiinpro.com/News/Detail/5611136?lang=vi-VN,ISS,0.30,0.0,2020-08-21,2020-08-20,Phát hành cổ phiếu,Share Issue
10,18150,ACB - Phát hành cổ phiếu trả cổ tức tỷ lệ 25%,ACB - Issues dividend shares at 25%,2021-06-03,2021-06-10,http://fiinpro.com/News/Detail/7805897?lang=vi-VN,ISS,0.25,0.0,2021-06-11,2021-06-10,Phát hành cổ phiếu,Share Issue
11,18153,ACB - Niêm yết bổ sung 106.101 cổ phiếu,"ACB - Lists additional 106,101 shares",2021-07-16,2022-04-26,http://fiinpro.com/News/Detail/8195547?lang=vi-VN,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
12,58604768,ACB - Niêm yết bổ sung 669.998.687 cổ phiếu,"ACB- Lists additional 669,998,687 shares",2025-06-27,2025-06-26,http://fiinpro.com/News/Detail/11613539?lang=v...,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
13,18136,Niêm yết thêm,,2013-09-03,2013-09-11,,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
14,18134,Niêm yết thêm,,2013-04-04,2013-04-12,,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
15,18139,Trả cổ tức bằng tiền mặt,,2015-05-05,2015-05-29,http://stoxvn.stox.vn/tin-tuc/250588/acb-1505-...,DIV,NaN,NaN,2015-05-19,2015-05-15,Trả cổ tức bằng tiền mặt,Cash Dividend
16,18149,ACB- Niêm yết bổ sung 498.821.183 cổ phiếu,"ACB- Lists additional 498,821,183 shares",2020-09-30,2020-10-05,http://fiinpro.com/News/Detail/5835123?lang=vi-VN,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
17,18145,ACB - Niêm yết bổ sung 162.673.713 cổ phiếu,ACB - Lists 162.673.713 additional shares,2018-11-01,2018-11-05,http://fiinpro.com/News/Detail/2517244?lang=vi-VN,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
18,18133,Trả cổ tức bằng tiền mặt,,2011-12-20,2012-01-18,,DIV,NaN,NaN,2012-01-05,2012-01-03,Trả cổ tức bằng tiền mặt,Cash Dividend
19,18141,ACB-Niêm yết bổ sung 89.627.390 cổ phiếu,"ACB-Lists 89,627,390 additional shares",2017-01-19,2017-01-25,http://fiinpro.com/News/Detail/329453?lang=vi-VN,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
20,18138,Niêm yết thêm,,2015-03-03,2015-03-16,http://stoxvn.stox.vn/tin-tuc/242552/acb-1603-...,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
21,18132,Niêm yết thêm,,2012-01-10,2012-01-16,,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
22,40234158,"ACB - Niêm yết bổ sung 582,607,554 cổ phiếu","ACB- Lists additional 582,607,554 shares",2024-06-28,2024-06-27,http://fiinpro.com/News/Detail/11231512?lang=v...,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
23,18130,Niêm yết thêm,,2011-03-07,2011-03-11,,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
24,9972801,"ACB - Niêm yết bổ sung 675,487,019 cổ phiếu","ACB- Lists additional 675,487,019 shares",2022-07-12,2022-07-06,http://fiinpro.com/News/Detail/10410854?lang=v...,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
25,23057391,ACB - Trả cổ tức Cả năm năm 2022 bằng tiền 100...,ACB - Pay cash dividend 2022 - Year at VND 100...,2023-05-25,2023-06-12,http://fiinpro.com/News/Detail/10793461?lang=v...,DIV,0.10,1000.0,2023-06-02,2023-06-01,Trả cổ tức bằng tiền mặt,Cash Dividend
26,38768795,ACB - Trả cổ tức Cả năm năm 2023 bằng tiền 100...,ACB - Pay cash dividend 2023 - Year at VND 100...,2024-05-24,2024-06-13,http://fiinpro.com/News/Detail/11196089?lang=v...,DIV,0.10,1000.0,2024-06-03,2024-05-31,Trả cổ tức bằng tiền mặt,Cash Dividend
27,56347802,ACB - Trả cổ tức Cả năm năm 2024 bằng tiền 100...,ACB - Pay cash dividend 2024 - Year at VND 100...,2025-05-16,2025-06-05,http://fiinpro.com/News/Detail/11586001?lang=v...,DIV,0.10,1000.0,2025-05-26,2025-05-23,Trả cổ tức bằng tiền mặt,Cash Dividend
28,18146,ACB-Phát hành cổ phiếu trả cổ tức tỷ lệ 30%,ACB-Issues dividend shares at 30%,2019-07-19,2019-07-25,http://fiinpro.com/News/Detail/3471990?lang=vi-VN,ISS,0.30,0.0,2019-07-26,2019-07-25,Phát hành cổ phiếu,Share Issue
29,7834550,ACB - Phát hành cổ phiếu trả cổ tức tỷ lệ 25%,ACB - Issues dividend shares at 25%,2022-05-25,2022-06-02,http://fiinpro.com/News/Detail/10341872?lang=v...,ISS,0.25,0.0,2022-06-03,2022-06-02,Phát hành cổ phiếu,Share Issue
30,23059999,ACB - Phát hành cổ phiếu trả cổ tức tỷ lệ 15%,ACB - Issues dividend shares at 15%,2023-05-25,2023-06-01,http://fiinpro.com/News/Detail/10793461?lang=v...,ISS,0.15,0.0,2023-06-02,2023-06-01,Phát hành cổ phiếu,Share Issue
31,24881283,"ACB - Niêm yết bổ sung 506,615,264 cổ phiếu","ACB- Lists additional 506,615,264 shares",2023-07-12,2023-07-06,http://fiinpro.com/News/Detail/10853128?lang=v...,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
32,38771599,ACB - Phát hành cổ phiếu trả cổ tức tỷ lệ 15%,ACB - Issues dividend shares at 15%,2024-05-24,2024-05-31,http://fiinpro.com/News/Detail/11196089?lang=v...,ISS,0.15,0.0,2024-06-03,2024-05-31,Phát hành cổ phiếu,Share Issue
33,18151,ACB - Niêm yết bổ sung 539.842.824 cổ phiếu,"ACB - Lists additional 539,842,824 shares",2021-07-16,2021-07-26,http://fiinpro.com/News/Detail/8195547?lang=vi-VN,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
34,56350780,ACB - Phát hành cổ phiếu trả cổ tức tỷ lệ 15%,ACB - Issues dividend shares at 15%,2025-05-16,2025-05-23,http://fiinpro.com/News/Detail/11586001?lang=v...,ISS,0.15,0.0,2025-05-26,2025-05-23,Phát hành cổ phiếu,Share Issue
35,18147,ACB - Niêm yết bổ sung 374.149.539 cổ phiếu,"ACB - Lists 374,149,539 additional shares",2019-09-11,2019-09-16,http://fiinpro.com/News/Detail/3722148?lang=vi-VN,AIS,0.00,0.0,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing
36,18143,"ACB - Niêm yết thêm 98,590,129 cổ phiếu","ACB - Lists additional 98,590,129 shares",2018-05-30,2018-06-04,https://owa.hnx.vn/ftp///cims/2018/5_W5/000000...,AIS,NaN,NaN,1753-01-01,1753-01-01,Niêm yết thêm,Additional Listing

In [1]:
from transformers import pipeline
model_path = '5CD-AI/Vietnamese-Sentiment-visobert'
sentiment_task = pipeline("sentiment-analysis", model=model_path, tokenizer=model_path)
sentiment_task("Miếng dán dễ xước , ko khít với dt 11 prm")

config.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/390M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/471k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Device set to use mps:0

[{'label': 'NEG', 'score': 0.998149037361145}]

In [11]:
import re
import pandas as pd
def extract_company_info(symbol)->pd.DataFrame:
    company = Company(symbol=symbol,source='VCI')
    return company.overview()

def extract_history(symbol):
    text = extract_company_info(symbol)['history'].iloc[0]
    pattern = r"-\s*(Ngày\s\d{2}/\d{2}/\d{4}|Năm\s\d{4}):\s*(.*?);"
    matches = re.findall(pattern, text)
    df = pd.DataFrame(matches, columns=["date", "detail"])
    return df
df=extract_history('ACB')

df.head()

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

              date                                             detail
0  Ngày 24/04/1993  Ngân hàng Thương mại Cổ phần Á Châu (ACB) được...
1  Ngày 17/02/1996                   Tăng vốn điều lệ lên 341 tỷ đồng
2         Năm 2005                Tăng vốn điều lệ lên 948,32 tỷ đồng
3  Ngày 14/02/2006             Tăng vốn điều lệ lên lên 1.100 tỷ đồng
4  Ngày 31/10/2006  Niêm yết trên Sở Giao dịch Chứng khoán Hà Nội ...